#! /usr/bin/env ChatGPTWeb-upload --ChatGPTWebAPI --new --loop
instruction:
emacs30 の tkita版 impatient-mode で、markdown-it + mermaid + highlight + mathjax
を xwidget + WbKit でブラウザ表示する。リアルタイムレンダリングしている。
これを、emacs 側で C-c C-e を押すとJSレンダリングが収まるのを待って、DOM の html 文を emacs 側に送信する機能を実装した。
impatient-mode.el と impatient-mode.js の最新版を以下に私が提示する。
inputs:
impatient-mode.js impatient-mode.js
impatient-mode.el impatient-mode.el
instruction:
このエラーを修復して。
Debugger entered--Lisp error: (wrong-type-argument xwidget-live-p #<window 13 on *xwidget-webkit: 信用創造.md*>)
  xwidget-webkit-execute-script(#<window 13 on *xwidget-webkit: 信用創造.md*> "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")
  (progn (let ((save-file (read-file-name "Save DOM to file: " nil nil nil "dom.html"))) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}"))
  (if win (progn (let ((save-file (read-file-name "Save DOM to file: " nil nil nil "dom.html"))) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")) (message "impatient-mode: WebKit バッファは表示されていません"))
  (let ((win (get-buffer-window xwb))) (if win (progn (let ((save-file (read-file-name "Save DOM to file: " nil nil nil "dom.html"))) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")) (message "impatient-mode: WebKit バッファは表示されていません")))
  (if xwb (let ((win (get-buffer-window xwb))) (if win (progn (let ((save-file (read-file-name "Save DOM to file: " nil nil nil "dom.html"))) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")) (message "impatient-mode: WebKit バッファは表示されていません"))) (message "impatient-mode: WebKit バッファが見つかりません"))
  (let ((xwb (car (imp--xwidget-webkit-buffer)))) (if xwb (let ((win (get-buffer-window xwb))) (if win (progn (let ((save-file ...)) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")) (message "impatient-mode: WebKit バッファは表示されていません"))) (message "impatient-mode: WebKit バッファが見つかりません")))
  (if (fboundp 'xwidget-webkit-execute-script) (let ((xwb (car (imp--xwidget-webkit-buffer)))) (if xwb (let ((win (get-buffer-window xwb))) (if win (progn (let (...) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")) (message "impatient-mode: WebKit バッファは表示されていません"))) (message "impatient-mode: WebKit バッファが見つかりません"))) (message "impatient-mode: xwidget WebKit 非対応"))
  #f(lambda () [t] (interactive nil) (if (fboundp 'xwidget-webkit-execute-script) (let ((xwb (car (imp--xwidget-webkit-buffer)))) (if xwb (let ((win (get-buffer-window xwb))) (if win (progn (let ((save-file (read-file-name "Save DOM to file: " nil nil nil "dom.html"))) (setq imp--xwidget-pending-save-file save-file)) (xwidget-webkit-execute-script win "if(window._imp_md && document.getElementById('marked')) {\n  window.webkit.messageHandlers.impDom.postMessage(document.getElementById('marked').innerHTML);\n}")) (message "impatient-mode: WebKit バッファは表示されていません"))) (message "impatient-mode: WebKit バッファが見つかりません"))) (message "impatient-mode: xwidget WebKit 非対応")))()
  funcall-interactively(#f(lambda () [t] (interactive nil) (if (fboundp 'xwidget-webkit-execute-script) (let ((xwb (car (imp--xwidget-webkit-buffer)))) (if xwb (let ((win ...)) (if win (progn ... ...) (message "impatient-mode: WebKit バッファは表示されていません"))) (message "impatient-mode: WebKit バッファが見つかりません"))) (message "impatient-mode: xwidget WebKit 非対応"))))
  command-execute(#f(lambda () [t] (interactive nil) (if (fboundp 'xwidget-webkit-execute-script) (let ((xwb (car (imp--xwidget-webkit-buffer)))) (if xwb (let ((win ...)) (if win (progn ... ...) (message "impatient-mode: WebKit バッファは表示されていません"))) (message "impatient-mode: WebKit バッファが見つかりません"))) (message "impatient-mode: xwidget WebKit 非対応"))))


